# Flujo de trabajo para iOS
workflows:

  build-and-deploy-ios:
    name: Build and Deploy iOS
    environment:
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Instalar cocoapods
        script: |
          gem install cocoapods
      - name: Inicializar podfile
        script: |
          pod init
      - name: Cd IOS
        script: |
          cd ios
      - name: Inicializar podfile
        script: |
          pod init
      - name: Install pods
        script: |
          pod install
      - name: Build ipa for distribution
        script: |
          xcodebuild -workspace AwesomeProject.xcworkspace -scheme AwesomeProject -configuration Release -archivePath build/AwesomeProject.xcarchive archive
          xcodebuild -exportArchive -archivePath build/AwesomeProject.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
    artifacts:
      - ios/build/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
 
# Flujo de trabajo para Android
  build-and-deploy-android:
    name: Build and Deploy Android
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Cd Android
        script: |
          cd android
      - name: Build Android
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      